# Generated by Django 3.2.20 on 2023-07-05 13:05

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField(blank=True)),
                ('excerpt', models.CharField(blank=True, max_length=300)),
                ('include_image', models.BooleanField(default=False)),
                ('image', models.ImageField(default='..xPress/default_post_image', upload_to='post_images')),
                ('include_audio', models.BooleanField(default=False)),
                ('audio', cloudinary.models.CloudinaryField(blank=True, max_length=255)),
                ('publish', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
