# Generated by Django 3.2.20 on 2023-07-20 10:29

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20230705_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='audio',
            field=cloudinary.models.CloudinaryField(blank=True, default='../xPress/default_post_image', max_length=255),
        ),
    ]
