# Generated by Django 3.2.20 on 2023-07-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='../xPress/default_avatar', upload_to='avatars/'),
        ),
    ]
