# Generated by Django 3.2.20 on 2023-09-17 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collage',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='collage',
            name='image2',
            field=models.ImageField(blank=True, default='../xPress/default_collage_image', upload_to='collage_images'),
        ),
    ]
