# Generated by Django 3.2.20 on 2023-09-17 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collages', '0004_auto_20230917_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collage',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='collage_images'),
        ),
        migrations.AlterField(
            model_name='collage',
            name='image10',
            field=models.ImageField(blank=True, null=True, upload_to='collage_images'),
        ),
        migrations.AlterField(
            model_name='collage',
            name='image11',
            field=models.ImageField(blank=True, null=True, upload_to='collage_images'),
        ),
        migrations.AlterField(
            model_name='collage',
            name='image12',
            field=models.ImageField(blank=True, null=True, upload_to='collage_images'),
        ),
        migrations.AlterField(
            model_name='collage',
            name='image13',
            field=models.ImageField(blank=True, null=True, upload_to='collage_images'),
        ),
        migrations.AlterField(
            model_name='collage',
            name='image14',
            field=models.ImageField(blank=True, null=True, upload_to='collage_images'),
        ),
        migrations.AlterField(
            model_name='collage',
            name='image15',
            field=models.ImageField(blank=True, null=True, upload_to='collage_images'),
        ),
        migrations.AlterField(
            model_name='collage',
            name='image16',
            field=models.ImageField(blank=True, null=True, upload_to='collage_images'),
        ),
        migrations.AlterField(
            model_name='collage',
            name='image17',
            field=models.ImageField(blank=True, null=True, upload_to='collage_images'),
        ),
        migrations.AlterField(
            model_name='collage',
            name='image18',
            field=models.ImageField(blank=True, null=True, upload_to='collage_images'),
        ),
        migrations.AlterField(
            model_name='collage',
            name='image19',
            field=models.ImageField(blank=True, null=True, upload_to='collage_images'),
        ),
        migrations.AlterField(
            model_name='collage',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='collage_images'),
        ),
        migrations.AlterField(
            model_name='collage',
            name='image20',
            field=models.ImageField(blank=True, null=True, upload_to='collage_images'),
        ),
        migrations.AlterField(
            model_name='collage',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='collage_images'),
        ),
        migrations.AlterField(
            model_name='collage',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='collage_images'),
        ),
        migrations.AlterField(
            model_name='collage',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='collage_images'),
        ),
        migrations.AlterField(
            model_name='collage',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to='collage_images'),
        ),
        migrations.AlterField(
            model_name='collage',
            name='image7',
            field=models.ImageField(blank=True, null=True, upload_to='collage_images'),
        ),
        migrations.AlterField(
            model_name='collage',
            name='image8',
            field=models.ImageField(blank=True, null=True, upload_to='collage_images'),
        ),
        migrations.AlterField(
            model_name='collage',
            name='image9',
            field=models.ImageField(blank=True, null=True, upload_to='collage_images'),
        ),
    ]
